# https://w3c.github.io/spec-prod/#deploy-to-github-pages
name: CI
on:
  pull_request: {}
  push:
    branches: [main]
jobs:
  main:
    name: Build, Validate and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          W3C_ECHIDNA_TOKEN: ${{ secrets.ECHIDNA_TOKEN }}
          W3C_WG_DECISION_URL: https://lists.w3.org/Archives/Public/public-webmachinelearning/2022Jun/0004.html
          W3C_BUILD_OVERRIDE: |
            status: NOTE-WD
            shortname: webmachinelearning-ethics
